# docker-compose.yml
version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000