services:
  - type: web
    name: django-docker-app
    env: docker
    plan: free
    region: singapore  # 東京はないので近場を選択
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
