# Generated by Django 5.2.4 on 2025-07-16 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_employee_qr_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='qr_code',
        ),
    ]
